name: Big_Plugin_outer_part
main: server_outer_part.Person_splitter
version: _ALPHA.2.0
author: Tyrolyean
commands:
   ping:
      description: The ping of the player.
      usage: /<command>
      permission: big.ping
      permission-message: You don't have <permission>
   lobby:
      description: Sets the Lobby.
      usage: /<command>
      permission: big.lobby
      permission-message: You don't have <permission>
   time:
      description: Gives the actual server-time.
      usage: /<command>
      permission: big.time
      permission-message: You don't have <permission>